# Site settings
title: Eric Gibbons
subtitle: Signal processing engineer
email: eric.gibbons (at) utah (dot) edu
description: MY PERSONAL WEBPAGE
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Eric Gibbons
street_address: 729 Arapeen Drive
city: Salt Lake City
state: UT
zip_code: 84108-1217
country: United States of America
phone:

# Social settings
500px_url:
facebook_url: http://facebook.com/ekgibbons
github_url: https://github.com/ekgibbons
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/gibbonsek
linkedin_url: https://www.linkedin.com/in/ekgibbons
pinterest_url:
slack_url:
twitter_url: https://twitter.com/ekgibbons

# Build settings
markdown: kramdown
