# Site settings
title: Editorial
subtitle: by HTML5 UP
email: ekgibbons@gmail.com
description: MY PERSONAL WEBPAGE
baseurl: "/ekgibbons" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: Palo Alto
state: CA
zip_code: 94306
country: United States of America
phone: 

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/ekgibbons
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/gibbonsek
linkedin_url: https://www.linkedin.com/in/ekgibbons
pinterest_url:
slack_url:
twitter_url: https://twitter.com/ekgibbons

# Build settings
markdown: kramdown
